### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by gilesknap** [dls-controls/dev-c7#21]
The current approach to versioning is missing:

- any way to tell which container version you have since it is tagged latest
- any way to tell which launcher version you have 
- any way to tie launcher and container together
  -  suggestion: make the launcher with embedded version and publish as a release Asset

**Comment by gilesknap** [comment]
If the launcher has its version embedded then it could also pull specific versions of the container image.

Downsides
- users have to explicitly pull a new launcher to get a new image
- historical image versions will clogg up the cache

**Comment by aawdls** [comment]
> any way to tell which container version you have since it is tagged latest
Can't an image have multiple tags? i.e. the version and also `latest`?

**Comment by gilesknap** [comment]
@aawdls yes but once you pull 'latest' to your local cache there is no easy way to tell which latest it was!

**Comment by gilesknap** [comment]
I've implemented a release asset for the script that defaults to its associated version of the image. Updated the quick start to reflect this.

Todo: I could add a feature to the script to flush old image versions out if local cache.
