### ISSUE TITLE
container time is UTC not BST

### ISSUE THREAD

**Issue by ronaldomercado** [dls-controls/dev-c7#30]
When performing a test build of a module on the dev-c7 container the generated script had the time off by one hour.

date also reports UTC, not BST
  $ date
  Mon Jul 11 14:14:54 UTC 2022

This might be a feature, rather than a bug?

**Comment by gilesknap** [comment]
Interesting - it's not intentional!

**Comment by ronaldomercado** [comment]
I found that this resets the container time to UK time
> sudo ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

I will try to add this to the Dockerfile and test

**Comment by gilesknap** [comment]
fixed in #54
