### ISSUE TITLE
edm button calling external program

### ISSUE THREAD

**Issue by ronaldomercado** [dls-controls/dev-c7#31]
I found a screen that uses a shell command button to display an image

The command is
eog /dls_sw/work/R3.14.11/support/insertionDevice/insertionDeviceApp/opi/edl8/Graphics/I05_Temperatures.tif

and that works okay on a workstation, not on the container

Another screen calls the shell command to display a manual/documentation
evince "$(which XV.gif| sed 's|data/XV.gif|documentation/vapour pressure LN2.pdf|')"

I am sure there's buttons that attempt to bring up a web browser.

**Comment by gilesknap** [comment]
Does it work if you first do
```
sudo yum install eog
```

If so please have a go at doing a PR using these instructions
https://dls-controls.github.io/dev-c7/main/reference/contributing.html

**Comment by gilesknap** [comment]
web browser is a little more interesting  - I guess we could install firefox inside the container 
I was a little reluctant to do this but it will probably work.

**Comment by gilesknap** [comment]
@ronaldomercado if you are going to try doing a PR please could you also see if adding firefox works?

Thanks.

**Comment by ronaldomercado** [comment]
I have tested evince and eog.
I will see if I can find screens that use firefox.

**Comment by gilesknap** [comment]
fixed in
https://github.com/dls-controls/dev-c7/releases/tag/2.0.2
thanks @ronaldomercado
