### ISSUE TITLE
java needed for flatdb

### ISSUE THREAD

**Issue by ronaldomercado** [dls-controls/dev-c7#40]
From a build of an epics module:

make[3]: Entering directory `/dls_sw/work/R3.14.12.7/support/insertionDevice/insertionDeviceApp/Db4V/O.linux-x86_64'
Flattening ../PLC4V_generic.vdb to produce ../O.Common/PLC4V_generic.template 
flatdb --disable-macro-warnings ../PLC4V_generic.vdb ../O.Common/PLC4V_generic.template 
/dls_sw/prod/tools/RHEL7-x86_64/defaults/bin/flatdb: line 6: java: command not found
make[3]: *** [../O.Common/PLC4V_generic.template] Error 127

**Comment by ronaldomercado** [comment]
This seems similar to issue #31 
It's solved with 
`sudo yum install java`

**Comment by gilesknap** [comment]
fixed in
https://github.com/dls-controls/dev-c7/releases/tag/2.0.2
thanks @ronaldomercado
