### ISSUE TITLE
c7 fails to start 'latest'

### ISSUE THREAD

**Issue by ronaldomercado** [dls-controls/dev-c7#85]
2023-Feb-23 11:33[rjq35657@pc0122 ~]$ c7
Creating new dev-c7 container version  Unknown ...
Error: error creating container storage: creating an ID-mapped copy of layer "cbd25db8783b1337fdc4973bb0616214cd78e3ce466dddcbc16e20f977471f9c": error during chown: link var/lib/yum/yumdb/G/849bf228e74ea0923a47774bf2964e49b3d2126e-GeoIP-1.5.0-14.el7-x86_64/from_repo_revision var/lib/yum/yumdb/b/017ea37b80011549ef304ba7cc3d71634462a244-blas-3.4.2-8.el7-x86_64/from_repo_revision: no such file or directory: exit status 1
Error: no container with name or ID "dev-c7" found: no such container
2023-Feb-23 11:33[rjq35657@pc0122 ~]$

**Comment by gilesknap** [comment]
@ronaldomercado  please try to get the latest container with
```
c7 -dp
```

**Comment by ronaldomercado** [comment]
Thanks. The problem is solved with that.

**Comment by gilesknap** [comment]
@ronaldomercado  - OK I think this is due to a change in the version of podman on our workstations.
I'd fixed the issue in the container build but you did not have the latest.

Is it worth adding a note to the docs to try -dp if you are having issues?
